mongodb:
  deployment:
    name: mongodb
    replicas: 1
    image: mongo
    containerPort: 27017
  service:
    name: mongodb-service
    port: 27017
    targetPort: 27017
  secret:
    name: mongodb-secret
  configmap:
    name: mongo-config

mongo-exp:
  deployment:
    name: mongo-exp
    image: mongo-express
    replicas: 1
    containerPort: 8081
  service:
    name: mongo-exp-service
    type: NodePort
    port: 8081
    targetPort: 8081
    nodePort: 30000