apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.deployment.name }}
  labels:
    app: {{ .Values.mongodb.deployment.name }}
spec:
  replicas: {{ .Values.mongodb.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.mongodb.deployment.name }}
        image: {{ .Values.mongodb.deployment.image }}
        ports:
        - containerPort: {{ .Values.mongodb.deployment.containerPort }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.secret.name }}
              key: mongo-root-username 
                  
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.secret.name }}
              key: mongo-root-password
      
